version: "3.7"

services:
  haproxy:
    image: haproxy:2.1.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"

  redis:
    image: redis:5.0.5-alpine3.9
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  azurite:
    image: arafato/azurite
    environment:
      executable: blob
    ports:
      - "10000:10000"
    expose:
      - "10000"

  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - "8000:8000"

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=http://dynamodb:8000"
      - "AWS_REGION=ap-northeast-1"
      - "AWS_ACCESS_KEY_ID=no"
      - "AWS_SECRET_ACCESS_KEY=no"

  httpd:
    image: httpd:2.4.41-alpine

  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - "8880:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./portal/dist:/var/www/public/portal"

  minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    command: "server /data"
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus:v2.15.2
    ports:
      - "9090:9090"

  # This rabbit hutch currently has one rabbit.
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - "15671:15671"
      - "15672:15672"

  errbit:
    image: errbit/errbit:v0.8.0
    ports:
      - "8845:8845"
    depends_on:
      - mongo
    environment:
      - PORT=8845
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit

  mongo:
    image: mongo:4.1
    ports:
      - "27017"

  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  logstash:
    image: logstash:7.5.1
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    volumes:
      - "./logstash/pipeline:/usr/share/logstash/pipeline"

  # See https://knowledge.sakura.ad.jp/2736/
  kibana:
    image: kibana:7.5.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - "./kibana/config:/usr/share/kibana/config"
