version: "3.7"

services:
  haproxy:
    image: haproxy:2.1.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"

  redis:
    image: redis:5.0.5-alpine3.9
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  azurite:
    image: arafato/azurite
    environment:
      executable: blob
    ports:
      - "10000:10000"
    expose:
      - "10000"

  dynamodb:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - "8000:8000"

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=http://dynamodb:8000"
      - "AWS_REGION=ap-northeast-1"
      - "AWS_ACCESS_KEY_ID=no"
      - "AWS_SECRET_ACCESS_KEY=no"

  httpd:
    image: httpd:2.4.41-alpine

  nginx:
    image: nginx:1.17.6-alpine

  minio:
    image: minio/minio:RELEASE.2020-01-03T19-12-21Z
    command: "server /data"
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus:v2.15.2
    ports:
      - "9090:9090"
